apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
# doc: https://carvel.dev/vendir/docs/v0.35.x/vendir-spec/

- path: src 
  contents:

  # validates checksums automatically from release notes

  - path: github.com/k3s-io/k3s
    githubRelease:
      slug: k3s-io/k3s
      tag: v1.24.17+k3s1 
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+). We use assetNames inside githubRelease instead of
      # includePaths at path level. Using includePaths downloads all assets and filter after.
      - "k3s"
      - "k3s-airgap-images-amd64.tar"
    # includePaths: # includes paths specify what should be included. by default all paths are included (optional)

  - path: github.com/derailed/k9s
    githubRelease:
      slug: derailed/k9s
      tag: v0.28.0
      disableAutoChecksumValidation: true 
      assetNames: # only download specific assets (optional; v0.12.0+), see k3s declaration for details.
      - "k9s_Linux_amd64.tar.gz"

  - path: github.com/containerd/nerdctl
    githubRelease:
      slug: containerd/nerdctl
      tag: v1.3.1
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+), see k3s declaration for details.
      - "nerdctl-1.3.1-linux-amd64.tar.gz"

