---
processes:
- name: k3s-server
  executable: /var/vcap/packages/k3s/k3s
  args:
  - server
  - --data-dir=/var/vcap/store/k3s-server
  - --default-local-storage-path=/var/vcap/store/k3s-server/local-storage-path
  - --private-registry=/var/vcap/packages/k3s-images/k3s-airgap-images-amd64.tar
  ephemeral_disk: true
  persistent_disk: true
  env:
  - K3S_KUBECONFIG_OUTPUT: /var/vcap/store/k3s-server/kubeconfig.yml
  limits:
  limits:
    memory: 2G
    open_files: 100000
  capabilities:
  - NET_BIND_SERVICE
#  additional_volumes:
#  - path: /var/vcap/store/k3s-server
#    writable: true
  unsafe:
    privileged: true
