---
processes:
- name: k3s-server
  executable: /var/vcap/packages/k3s/k3s
  args:
  - server
  - --data-dir=/var/vcap/store/k3s-server
  - --private-registry=/var/vcap/packages/k3s-images
  - --basic-auth-file=/var/vcap/store/k3s-server/cred/passwd
  - --cert-dir=/var/vcap/store/k3s-server/tls/temporary-certs
  - --client-ca-file=/var/vcap/store/k3s-server/tls/client-ca.crt
  - --kubelet-certificate-authority=/var/vcap/store/k3s-server/tls/server-ca.crt
  - --kubelet-client-certificate=/var/vcap/store/k3s-server/tls/client-kube-apiserver.crt
  - --kubelet-client-key=/var/vcap/store/k3s-server/tls/client-kube-apiserver.key
  - --proxy-client-cert-file=/var/vcap/store/k3s-server/tls/client-auth-proxy.crt
  - --proxy-client-key-file=/var/vcap/store/k3s-server/tls/client-auth-proxy.key
  - --requestheader-client-ca-file=/var/vcap/store/k3s-server/tls/request-header-ca.crt
  - --service-account-key-file=/var/vcap/store/k3s-server/tls/service.key
  - --service-account-signing-key-file=/var/vcap/store/k3s-server/tls/service.key 
  - --tls-cert-file=/var/vcap/store/k3s-server/tls/serving-kube-apiserver.crt 
  - --tls-private-key-file=/var/vcap/store/k3s-server/tls/serving-kube-apiserver.key
  ephemeral_disk: true
  persistent_disk: true
  limits:
    open_files: 100000
  limits:
    memory: 1G
    open_files: 1024
  capabilities:
  - NET_BIND_SERVICE
#  additional_volumes:
#  - path: /var/vcap/store/k3s-server
#    writable: true
  unsafe:
    privileged: true
