---
processes:
- name: k3s-server
  executable: /var/vcap/packages/k3s/k3s
  args:
  - server
  - --data-dir /var/vcap/store/k3s-server
  - --private-registry /var/vcap/packages/k3s-images
  ephemeral_disk: true
  persistent_disk: true
  limits:
    open_files: 100000
   
  env: []
  limits:
    memory: 1G
    open_files: 1024
  capabilities:
  - NET_BIND_SERVICE
