---
processes:
- name: k3s-agent
  executable: /var/vcap/packages/k3s-agent/bin/k3s-agent
  args: []
  ephemeral_disk: true
  persistent_disk: true 
  env:
   TOKEN: <%= p("k3s.token") %>
  limits:
    memory: 1G
    open_files: 1024

# examples/docs at:
# - https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/test-server/templates/bpm.yml.erb
# - https://github.com/cloudfoundry-incubator/bpm-release/tree/master/docs
